version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=development
    command: npm run dev
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped
    # Make sure the container stays running
    tty: true
    stdin_open: true 